import {
  adaptiveProjectSchema,
  type AdaptiveProject,
  type Civilization,
  type Phase,
  type PlacementPolicy,
  type ResponseRule,
  type StrategyStep,
} from "./model";

const phase = (
  villagers: number,
  food: number,
  wood: number,
  gold: number,
  stone: number,
  milestone?: string,
): Phase => ({
  villagers,
  resources: { food, wood, gold, stone },
  ...(milestone ? { milestone } : {}),
});

const placement = (value: PlacementPolicy): PlacementPolicy => value;

const commonPlacements = (): PlacementPolicy[] => [
  placement({
    id: "home-housing",
    label: "Protect housing near the town center",
    building: "house",
    anchor: "home-town-center",
    direction: "around",
    distance: 0,
    spacing: 0,
    strict: false,
    observedOnly: false,
    fallback: [
      {
        anchor: "home-town-center",
        direction: "around",
        distance: 0,
        spacing: 0,
      },
      { anchor: "production", direction: "around", distance: 0, spacing: 0 },
    ],
  }),
  placement({
    id: "wood-camp",
    label: "Keep the first lumber camp close to home",
    building: "lumber-camp",
    anchor: "home-town-center",
    direction: "around",
    distance: 0,
    spacing: 0,
    strict: false,
    observedOnly: false,
    fallback: [
      {
        anchor: "home-town-center",
        direction: "around",
        distance: 0,
        spacing: 0,
      },
      { anchor: "production", direction: "around", distance: 0, spacing: 0 },
    ],
  }),
  placement({
    id: "forward-range",
    label: "Place a pressure range toward the discovered enemy",
    building: "archery-range",
    anchor: "forward-pressure",
    direction: "toward-enemy",
    distance: 8,
    spacing: 0,
    strict: false,
    observedOnly: true,
    fallback: [
      { anchor: "production", direction: "around", distance: 0, spacing: 0 },
      {
        anchor: "home-town-center",
        direction: "around",
        distance: 0,
        spacing: 0,
      },
    ],
  }),
  placement({
    id: "defensive-tower",
    label: "Protect the threatened town edge",
    building: "watch-tower",
    anchor: "home-town-center",
    direction: "toward-enemy",
    distance: 10,
    spacing: 0,
    strict: false,
    observedOnly: true,
    fallback: [
      {
        anchor: "home-town-center",
        direction: "around",
        distance: 0,
        spacing: 0,
      },
      { anchor: "production", direction: "around", distance: 0, spacing: 0 },
    ],
  }),
  placement({
    id: "castle-defense",
    label: "Put the castle between home and the pressure",
    building: "castle",
    anchor: "home-town-center",
    direction: "toward-enemy",
    distance: 12,
    spacing: 0,
    strict: false,
    observedOnly: true,
    fallback: [
      {
        anchor: "home-town-center",
        direction: "around",
        distance: 0,
        spacing: 0,
      },
      { anchor: "production", direction: "around", distance: 0, spacing: 0 },
    ],
  }),
];

const housingResponse = (): ResponseRule => ({
  id: "repair-housing",
  label: "Restore housing before the next queue",
  enabled: true,
  priority: 95,
  trigger: {
    kind: "housing-shortage",
    threshold: 2,
    sustainedSeconds: 5,
    observation: "observed",
  },
  actions: [
    {
      kind: "build",
      building: "house",
      count: 1,
      placementId: "home-housing",
      priority: 100,
    },
  ],
  recovery: { kind: "threshold", threshold: 4 },
  cooldownSeconds: 25,
  limits: {
    maxDurationSeconds: 120,
    maxWorkers: 2,
    emergencySpend: { food: 0, wood: 100, gold: 0, stone: 0 },
    allowPivot: false,
  },
});

const raidResponse = (): ResponseRule => ({
  id: "defend-raid",
  label: "Defend the town when it is attacked",
  enabled: true,
  priority: 100,
  trigger: { kind: "raid", sustainedSeconds: 2, observation: "observed" },
  actions: [
    { kind: "defend", unit: "archer", priority: 100 },
    { kind: "retreat", unit: "archer", priority: 90 },
  ],
  recovery: { kind: "timeout", afterSeconds: 30 },
  cooldownSeconds: 45,
  limits: {
    maxDurationSeconds: 90,
    maxWorkers: 0,
    emergencySpend: { food: 0, wood: 0, gold: 0, stone: 0 },
    allowPivot: false,
  },
});

const forwardResponse = (): ResponseRule => ({
  id: "answer-forward-defense",
  label: "Answer a forward building with defense",
  enabled: true,
  priority: 88,
  trigger: {
    kind: "forward-defense",
    threshold: 1,
    sustainedSeconds: 5,
    observation: "observed",
  },
  actions: [
    {
      kind: "build",
      building: "watch-tower",
      count: 1,
      placementId: "defensive-tower",
      priority: 90,
    },
    { kind: "defend", unit: "spearman-line", priority: 80 },
  ],
  recovery: { kind: "timeout", afterSeconds: 60 },
  cooldownSeconds: 90,
  limits: {
    maxDurationSeconds: 180,
    maxWorkers: 3,
    emergencySpend: { food: 0, wood: 100, gold: 0, stone: 150 },
    allowPivot: false,
  },
});

const placementResponse = (): ResponseRule => ({
  id: "recover-placement",
  label: "Retry a blocked foundation with the next fallback",
  enabled: true,
  priority: 82,
  trigger: {
    kind: "placement-blocked",
    threshold: 1,
    sustainedSeconds: 10,
    observation: "observed",
  },
  actions: [
    { kind: "reset-placement", building: "archery-range", priority: 80 },
  ],
  recovery: { kind: "timeout", afterSeconds: 40 },
  cooldownSeconds: 60,
  limits: {
    maxDurationSeconds: 120,
    maxWorkers: 2,
    emergencySpend: { food: 0, wood: 0, gold: 0, stone: 0 },
    allowPivot: false,
  },
});

const counterResponse = (civ: Civilization): ResponseRule => ({
  id: "answer-counter-unit",
  label:
    civ === "portuguese"
      ? "Protect Organ Guns from cavalry"
      : "Protect the ranged core from cavalry",
  enabled: true,
  priority: 78,
  trigger: {
    kind: "counter-army",
    unit: "knight-line",
    threshold: 2,
    sustainedSeconds: 8,
    observation: "either",
  },
  actions: [
    {
      kind: "train",
      unit: civ === "portuguese" ? "pikeman" : "spearman-line",
      count: 4,
      priority: 85,
    },
    {
      kind: "retreat",
      unit: civ === "portuguese" ? "organ-gun" : "archer",
      priority: 95,
    },
  ],
  recovery: { kind: "timeout", afterSeconds: 60 },
  cooldownSeconds: 90,
  limits: {
    maxDurationSeconds: 180,
    maxWorkers: 4,
    emergencySpend: { food: 200, wood: 120, gold: 0, stone: 0 },
    allowPivot: false,
  },
});

const recoveryResponses = (civilization: Civilization): ResponseRule[] => [
  {
    id: "foundation-lost",
    label: "Rebuild a lost production foundation",
    enabled: false,
    priority: 80,
    trigger: {
      kind: "foundation-lost",
      sustainedSeconds: 5,
      observation: "observed",
    },
    actions: [
      {
        kind: "build",
        building: civilization === "portuguese" ? "castle" : "archery-range",
        count: 1,
        placementId:
          civilization === "portuguese" ? "castle-defense" : "forward-range",
        priority: 80,
      },
    ],
    recovery: { kind: "timeout", afterSeconds: 45 },
    cooldownSeconds: 90,
    limits: {
      maxDurationSeconds: 150,
      maxWorkers: 3,
      emergencySpend:
        civilization === "portuguese"
          ? { food: 0, wood: 0, gold: 0, stone: 650 }
          : { food: 0, wood: 175, gold: 0, stone: 0 },
      allowPivot: false,
    },
  },
  {
    id: "resource-depleted",
    label: "Shift the economy after observed gold depletion",
    enabled: false,
    priority: 68,
    trigger: {
      kind: "resource-depleted",
      resource: "gold",
      threshold: 2,
      sustainedSeconds: 20,
      observation: "observed",
    },
    actions: [
      {
        kind: "allocate",
        resources: { food: 40, wood: 45, gold: 10, stone: 5 },
        priority: 60,
      },
    ],
    recovery: { kind: "timeout", afterSeconds: 90 },
    cooldownSeconds: 180,
    limits: {
      maxDurationSeconds: 180,
      maxWorkers: 0,
      emergencySpend: { food: 0, wood: 0, gold: 0, stone: 0 },
      allowPivot: false,
    },
  },
  {
    id: "builder-lost",
    label: "Reassign construction after inferred builder loss",
    enabled: false,
    priority: 75,
    trigger: {
      kind: "builder-lost",
      sustainedSeconds: 5,
      observation: "observed",
    },
    actions: [
      {
        kind: "allocate",
        resources: { food: 50, wood: 30, gold: 10, stone: 10 },
        priority: 50,
      },
    ],
    recovery: { kind: "timeout", afterSeconds: 30 },
    cooldownSeconds: 60,
    limits: {
      maxDurationSeconds: 90,
      maxWorkers: 2,
      emergencySpend: { food: 0, wood: 0, gold: 0, stone: 0 },
      allowPivot: false,
    },
  },
  {
    id: "resource-threatened",
    label:
      "Protect a threatened resource (use raid response for native export)",
    enabled: false,
    priority: 70,
    trigger: {
      kind: "resource-threatened",
      resource: "gold",
      sustainedSeconds: 8,
      observation: "observed",
    },
    actions: [{ kind: "defend", unit: "spearman-line", priority: 60 }],
    recovery: { kind: "timeout", afterSeconds: 45 },
    cooldownSeconds: 90,
    limits: {
      maxDurationSeconds: 120,
      maxWorkers: 0,
      emergencySpend: { food: 0, wood: 0, gold: 0, stone: 0 },
      allowPivot: false,
    },
  },
  {
    id: "development-stalled",
    label: "Recover a stalled development plan",
    enabled: true,
    priority: 84,
    trigger: {
      kind: "development-stalled",
      sustainedSeconds: 30,
      observation: "either",
    },
    actions: [
      {
        kind: "allocate",
        resources:
          civilization === "portuguese"
            ? { food: 35, wood: 30, gold: 20, stone: 15 }
            : { food: 40, wood: 35, gold: 20, stone: 5 },
        priority: 70,
      },
      {
        kind: "pivot",
        stepIds: [civilization === "portuguese" ? "castle" : "ranges"],
        priority: 60,
      },
    ],
    recovery: { kind: "timeout", afterSeconds: 120 },
    cooldownSeconds: 180,
    limits: {
      maxDurationSeconds: 240,
      maxWorkers: 6,
      emergencySpend: { food: 100, wood: 100, gold: 50, stone: 0 },
      allowPivot: true,
    },
  },
];

const boundedAlternativeResponses = (
  civilization: Civilization,
): ResponseRule[] =>
  civilization === "britons"
    ? [
        {
          id: "briton-skirmisher-support",
          label: "Add skirmishers against observed archers",
          enabled: false,
          priority: 74,
          trigger: {
            kind: "counter-army",
            unit: "archer",
            threshold: 4,
            sustainedSeconds: 10,
            observation: "observed",
          },
          actions: [
            { kind: "train", unit: "skirmisher-line", count: 6, priority: 80 },
          ],
          recovery: { kind: "timeout", afterSeconds: 75 },
          cooldownSeconds: 120,
          limits: {
            maxDurationSeconds: 180,
            maxWorkers: 0,
            emergencySpend: { food: 150, wood: 210, gold: 0, stone: 0 },
            allowPivot: false,
          },
        },
        {
          id: "briton-siege-support",
          label: "Add siege against an observed forward defense",
          enabled: false,
          priority: 72,
          trigger: {
            kind: "forward-defense",
            threshold: 2,
            sustainedSeconds: 12,
            observation: "observed",
          },
          actions: [
            { kind: "train", unit: "mangonel-line", count: 2, priority: 80 },
          ],
          recovery: { kind: "timeout", afterSeconds: 90 },
          cooldownSeconds: 150,
          limits: {
            maxDurationSeconds: 210,
            maxWorkers: 0,
            emergencySpend: { food: 0, wood: 320, gold: 270, stone: 0 },
            allowPivot: false,
          },
        },
      ]
    : [
        {
          id: "castle-unavailable-archer-fallback",
          label:
            "Enable the archer fallback after an inferred castle-production stall",
          enabled: false,
          priority: 76,
          trigger: {
            kind: "foundation-lost",
            sustainedSeconds: 12,
            observation: "observed",
          },
          actions: [
            {
              kind: "pivot",
              stepIds: ["fallback-range", "fallback-archers"],
              priority: 80,
            },
          ],
          recovery: { kind: "timeout", afterSeconds: 120 },
          cooldownSeconds: 180,
          limits: {
            maxDurationSeconds: 240,
            maxWorkers: 4,
            emergencySpend: { food: 0, wood: 175, gold: 0, stone: 0 },
            allowPivot: true,
          },
        },
      ];

const commonMicro = (): AdaptiveProject["micro"] => ({
  ownership: "exclusive" as const,
  globalReactionIntervalSeconds: 4,
  ranged: {
    enabled: true,
    aggression: "balanced" as const,
    targetPriorities: ["ranged", "siege", "buildings"],
    retreatHealthPercent: 25,
    regroupSeconds: 8,
    searchIntervalSeconds: 4,
    groupSize: 20,
    observedOnly: true,
  },
  melee: {
    enabled: false,
    aggression: "balanced" as const,
    targetPriorities: ["closest", "highest-threat"],
    retreatHealthPercent: 25,
    regroupSeconds: 10,
    searchIntervalSeconds: 5,
    groupSize: 20,
    observedOnly: true,
  },
  siege: {
    enabled: true,
    aggression: "cautious" as const,
    targetPriorities: ["buildings", "siege"],
    retreatHealthPercent: 30,
    regroupSeconds: 12,
    searchIntervalSeconds: 6,
    groupSize: 8,
    observedOnly: true,
  },
  screening: {
    enabled: true,
    aggression: "balanced" as const,
    targetPriorities: ["ranged", "siege"],
    retreatHealthPercent: 30,
    regroupSeconds: 8,
    searchIntervalSeconds: 5,
    groupSize: 12,
    observedOnly: true,
  },
});

const britonSteps = (): StrategyStep[] => [
  {
    id: "lumber-camp",
    label: "Secure the first woodline",
    phase: "dark",
    priority: 95,
    enabled: true,
    kind: "build",
    building: "lumber-camp",
    count: 1,
    placementId: "wood-camp",
  },
  {
    id: "mill",
    label: "Prepare food income",
    phase: "dark",
    priority: 90,
    enabled: true,
    kind: "build",
    building: "mill",
    count: 1,
  },
  {
    id: "loom",
    label: "Research Loom",
    phase: "dark",
    priority: 80,
    enabled: true,
    kind: "research",
    research: "loom",
  },
  {
    id: "feudal-age",
    label: "Reach Feudal Age",
    phase: "dark",
    priority: 100,
    enabled: true,
    kind: "research",
    research: "feudal-age",
  },
  {
    id: "barracks",
    label: "Open the barracks",
    phase: "feudal",
    priority: 92,
    enabled: true,
    kind: "build",
    building: "barracks",
    count: 1,
  },
  {
    id: "ranges",
    label: "Add ranged production",
    phase: "feudal",
    priority: 95,
    enabled: true,
    kind: "build",
    building: "archery-range",
    count: 2,
    placementId: "forward-range",
  },
  {
    id: "feudal-archers",
    label: "Build the first ranged force",
    phase: "feudal",
    priority: 90,
    enabled: true,
    kind: "train",
    unit: "archer",
    count: 12,
    productionBuilding: "archery-range",
  },
  {
    id: "feudal-blacksmith",
    label: "Open ranged upgrades",
    phase: "feudal",
    priority: 84,
    enabled: true,
    kind: "build",
    building: "blacksmith",
    count: 1,
  },
  {
    id: "feudal-fletching",
    label: "Research Fletching",
    phase: "feudal",
    priority: 83,
    enabled: true,
    kind: "research",
    research: "ri-fletching",
  },
  {
    id: "castle-age",
    label: "Reach Castle Age",
    phase: "feudal",
    priority: 78,
    enabled: true,
    kind: "research",
    research: "castle-age",
  },
  {
    id: "castle-crossbows",
    label: "Upgrade the ranged core",
    phase: "castle",
    priority: 88,
    enabled: true,
    kind: "research",
    research: "ri-crossbow",
  },
  {
    id: "castle-bodkin",
    label: "Research Bodkin Arrow",
    phase: "castle",
    priority: 84,
    enabled: true,
    kind: "research",
    research: "ri-bodkin-arrow",
  },
  {
    id: "castle-town-center",
    label: "Expand to a second town center",
    phase: "castle",
    priority: 82,
    enabled: true,
    kind: "build",
    building: "town-center",
    count: 2,
  },
  {
    id: "castle-army",
    label: "Grow the Castle Age ranged army",
    phase: "castle",
    priority: 90,
    enabled: true,
    kind: "train",
    unit: "crossbowman",
    count: 30,
    productionBuilding: "archery-range",
  },
  {
    id: "castle-university",
    label: "Open Imperial support technologies",
    phase: "castle",
    priority: 78,
    enabled: true,
    kind: "build",
    building: "university",
    count: 1,
  },
  {
    id: "castle-siege-workshop",
    label: "Open siege production and the second Imperial prerequisite",
    phase: "castle",
    priority: 76,
    enabled: true,
    kind: "build",
    building: "siege-workshop",
    count: 1,
  },
  {
    id: "imperial-age",
    label: "Reach Imperial Age",
    phase: "castle",
    priority: 72,
    enabled: true,
    kind: "research",
    research: "imperial-age",
  },
  {
    id: "imperial-bracer",
    label: "Finish the ranged technology line",
    phase: "imperial",
    priority: 82,
    enabled: true,
    kind: "research",
    research: "ri-bracer",
  },
  {
    id: "imperial-arbalest",
    label: "Upgrade the army to Arbalest",
    phase: "imperial",
    priority: 88,
    enabled: true,
    kind: "research",
    research: "ri-arbalest",
  },
  {
    id: "imperial-army",
    label: "Replace losses and maintain the army",
    phase: "imperial",
    priority: 95,
    enabled: true,
    kind: "train",
    unit: "arbalest",
    count: 50,
    productionBuilding: "archery-range",
  },
  {
    id: "imperial-castle",
    label: "Add a castle for siege support",
    phase: "imperial",
    priority: 70,
    enabled: true,
    kind: "build",
    building: "castle",
    count: 1,
    placementId: "castle-defense",
  },
  {
    id: "post-imperial",
    label: "Enter post-Imperial sustain phase",
    phase: "postImperial",
    priority: 50,
    enabled: true,
    kind: "milestone",
    milestone: "post-imperial-sustain",
  },
  {
    id: "post-siege",
    label: "Add siege support",
    phase: "postImperial",
    priority: 65,
    enabled: true,
    kind: "train",
    unit: "trebuchet",
    count: 4,
    productionBuilding: "castle",
  },
];

const portugueseSteps = (): StrategyStep[] => [
  {
    id: "lumber-camp",
    label: "Secure the first woodline",
    phase: "dark",
    priority: 95,
    enabled: true,
    kind: "build",
    building: "lumber-camp",
    count: 1,
    placementId: "wood-camp",
  },
  {
    id: "mill",
    label: "Prepare food income",
    phase: "dark",
    priority: 90,
    enabled: true,
    kind: "build",
    building: "mill",
    count: 1,
  },
  {
    id: "loom",
    label: "Research Loom",
    phase: "dark",
    priority: 82,
    enabled: true,
    kind: "research",
    research: "loom",
  },
  {
    id: "feudal-age",
    label: "Reach Feudal Age",
    phase: "dark",
    priority: 100,
    enabled: true,
    kind: "research",
    research: "feudal-age",
  },
  {
    id: "market",
    label: "Open the fast-Castle market",
    phase: "feudal",
    priority: 96,
    enabled: true,
    kind: "build",
    building: "market",
    count: 1,
  },
  {
    id: "blacksmith",
    label: "Open the fast-Castle blacksmith",
    phase: "feudal",
    priority: 94,
    enabled: true,
    kind: "build",
    building: "blacksmith",
    count: 1,
  },
  {
    id: "castle-age",
    label: "Reach Castle Age quickly",
    phase: "feudal",
    priority: 100,
    enabled: true,
    kind: "research",
    research: "castle-age",
  },
  {
    id: "castle",
    label: "Secure the Organ Gun production castle",
    phase: "castle",
    priority: 98,
    enabled: true,
    kind: "build",
    building: "castle",
    count: 1,
    placementId: "castle-defense",
  },
  {
    id: "organ-guns",
    label: "Build the Organ Gun core",
    phase: "castle",
    priority: 98,
    enabled: true,
    kind: "train",
    unit: "organ-gun",
    count: 12,
    productionBuilding: "castle",
  },
  {
    id: "castle-barracks",
    label: "Add support production",
    phase: "castle",
    priority: 82,
    enabled: true,
    kind: "build",
    building: "barracks",
    count: 1,
  },
  {
    id: "castle-pikeman",
    label: "Upgrade spear support",
    phase: "castle",
    priority: 80,
    enabled: true,
    kind: "research",
    research: "ri-pikeman",
  },
  {
    id: "castle-support",
    label: "Add pike support",
    phase: "castle",
    priority: 78,
    enabled: true,
    kind: "train",
    unit: "pikeman",
    count: 8,
    productionBuilding: "barracks",
  },
  {
    id: "imperial-age",
    label: "Reach Imperial Age",
    phase: "castle",
    priority: 75,
    enabled: true,
    kind: "research",
    research: "imperial-age",
  },
  {
    id: "imperial-university",
    label: "Open Imperial technologies",
    phase: "imperial",
    priority: 90,
    enabled: true,
    kind: "build",
    building: "university",
    count: 1,
  },
  {
    id: "imperial-chemistry",
    label: "Improve gunpowder damage",
    phase: "imperial",
    priority: 88,
    enabled: true,
    kind: "research",
    research: "ri-chemistry",
  },
  {
    id: "imperial-guns",
    label: "Maintain the Organ Gun army",
    phase: "imperial",
    priority: 96,
    enabled: true,
    kind: "train",
    unit: "organ-gun",
    count: 35,
    productionBuilding: "castle",
  },
  {
    id: "fallback-range",
    label: "Optional archer fallback range",
    phase: "castle",
    priority: 55,
    enabled: false,
    kind: "build",
    building: "archery-range",
    count: 1,
    placementId: "forward-range",
  },
  {
    id: "fallback-archers",
    label:
      "Optional archer fallback force while castle production is unavailable",
    phase: "castle",
    priority: 54,
    enabled: false,
    kind: "train",
    unit: "archer",
    count: 16,
    productionBuilding: "archery-range",
    whileBuildingMissing: "castle",
  },
  {
    id: "post-imperial",
    label: "Enter post-Imperial sustain phase",
    phase: "postImperial",
    priority: 50,
    enabled: true,
    kind: "milestone",
    milestone: "post-imperial-sustain",
  },
  {
    id: "post-trebuchets",
    label: "Support the guns with siege",
    phase: "postImperial",
    priority: 65,
    enabled: true,
    kind: "train",
    unit: "trebuchet",
    count: 4,
    productionBuilding: "castle",
  },
];

const responseSet = (civilization: Civilization): ResponseRule[] => [
  housingResponse(),
  raidResponse(),
  forwardResponse(),
  placementResponse(),
  counterResponse(civilization),
  ...recoveryResponses(civilization),
  ...boundedAlternativeResponses(civilization),
];

export function createPreset(civilization: Civilization): AdaptiveProject {
  const isBritons = civilization === "britons";
  const value: AdaptiveProject = {
    schemaVersion: 2,
    name: isBritons ? "Greenwood Adaptive Archers" : "Portuguese Castle Guns",
    civilization,
    scenario: {
      mapStyle: "arabia-1v1",
      playerCount: 2,
      resources: "standard",
      startingAge: "dark",
      populationLimit: 200,
    },
    phases: isBritons
      ? {
          dark: phase(22, 60, 40, 0, 0),
          feudal: phase(40, 40, 40, 20, 0),
          castle: phase(60, 35, 35, 25, 5),
          imperial: phase(90, 30, 35, 25, 10),
          postImperial: phase(120, 25, 35, 25, 15, "post-imperial-sustain"),
        }
      : {
          dark: phase(21, 50, 40, 10, 0),
          feudal: phase(36, 40, 25, 20, 15),
          castle: phase(58, 25, 25, 20, 30),
          imperial: phase(88, 25, 30, 25, 20),
          postImperial: phase(120, 25, 35, 25, 15, "post-imperial-sustain"),
        },
    steps: isBritons ? britonSteps() : portugueseSteps(),
    responses: responseSet(civilization),
    placements: commonPlacements(),
    micro: commonMicro(),
    limits: {
      allowPivots: true,
      allowEmergencySpend: true,
      maxEmergencySpend: { food: 300, wood: 300, gold: 200, stone: 200 },
      maxConcurrentResponses: 2,
      minimumResponseSeconds: 10,
      strictPlacement: false,
    },
  };
  return adaptiveProjectSchema.parse(value);
}
