import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { unzipSync, strFromU8 } from 'fflate';
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1536,height:1024}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
const evidence='design-review/builds/adaptive-editor/legacy';
await fs.mkdir(evidence,{recursive:true});
await page.goto('http://127.0.0.1:5173');
await page.getByRole('button',{name:'Open version-1 editor',exact:true}).click();
await page.getByRole('heading',{name:'Build your economy'}).waitFor();
await page.screenshot({path:`${evidence}/desktop.png`});
await page.getByLabel('Villager target',{exact:true}).fill('24');
await page.getByRole('button',{name:'Export',exact:true}).click();
assert.match(await page.getByLabel('Generated AI script').innerText(),/unit-type-count-total villager < 24/);
await page.getByRole('button',{name:'Undo',exact:true}).click();
assert.match(await page.getByLabel('Generated AI script').innerText(),/unit-type-count-total villager < 22/);
await page.getByRole('button',{name:'Redo',exact:true}).click();
assert.match(await page.getByLabel('Generated AI script').innerText(),/unit-type-count-total villager < 24/);
const downloadPromise=page.waitForEvent('download');
await page.getByRole('button',{name:'Download bot ZIP'}).click();
const download=await downloadPromise;
assert.equal(download.suggestedFilename(),'Greenwood Archers.zip');
const files=unzipSync(await fs.readFile(await download.path()));
assert.equal(files['Greenwood Archers.ai'].length,0);
assert.match(strFromU8(files['Greenwood Archers.per']),/unit-type-count-total villager < 24/);
assert.equal(JSON.parse(strFromU8(files['Greenwood Archers.workshop.json'])).dark.villagers,24);
const projectDownloadPromise=page.waitForEvent('download');
await page.getByRole('button',{name:'Save project',exact:true}).click();
const projectDownload=await projectDownloadPromise;
const saved=JSON.parse(await fs.readFile(await projectDownload.path(),'utf8'));
assert.equal(saved.dark.villagers,24);
await page.getByLabel('Open project file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":99}')});
await expect(page.getByRole('status')).toContainText('schemaVersion');
assert.match(await page.getByLabel('Generated AI script').innerText(),/unit-type-count-total villager < 24/);
await page.getByLabel('Open project file').setInputFiles('examples/Greenwood Archers.workshop.json');
await expect(page.getByRole('status')).toContainText('Opened Greenwood Archers');
assert.match(await page.getByLabel('Generated AI script').innerText(),/unit-type-count-total villager < 22/);
await page.getByRole('button',{name:'Economy',exact:true}).click();
await page.getByLabel('Food',{exact:true}).fill('50');
await page.getByRole('button',{name:'Export',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'Download bot ZIP'}).isEnabled(),false);
await page.getByRole('button',{name:'Undo',exact:true}).click();
await page.reload();
assert.equal(await page.getByLabel('Villager target',{exact:true}).inputValue(),'22');
await page.setViewportSize({width:1280,height:800});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),1280);
await page.screenshot({path:`${evidence}/laptop.png`});
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
await page.screenshot({path:`${evidence}/mobile.png`,fullPage:true});
for (const section of ['Buildings','Army','Strategy','Testing','Export']) {
  await page.getByRole('button',{name:section,exact:true}).click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390,section+' overflow');
}
await page.setViewportSize({width:1536,height:1024});
await page.getByRole('button',{name:'Export',exact:true}).click();
await page.screenshot({path:`${evidence}/export.png`});
// Damaged local drafts survive edits and reload, and remain downloadable.
await page.evaluate(() => localStorage.setItem('ai-workshop.project.v1', '{damaged original draft'));
await page.reload();
await expect(page.getByRole('button',{name:'Download recovery copy'})).toBeVisible();
await page.getByLabel('Villager target',{exact:true}).fill('23');
await page.reload();
await expect(page.getByLabel('Villager target',{exact:true})).toHaveValue('23');
const recoveryWait = page.waitForEvent('download');
await page.getByRole('button',{name:'Download recovery copy'}).click();
const recoveryDownload = await recoveryWait;
assert.equal(await fs.readFile(await recoveryDownload.path(),'utf8'),'{damaged original draft');
assert.deepEqual(errors,[]);
await browser.close();
console.log('PASS: edit, undo/redo, save, valid/invalid imports, actual ZIP contents, export blocking, reload, all mobile sections, desktop/laptop/mobile screenshots, no page errors.');
